# Generated by Django 4.0.4 on 2022-04-26 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Nombre del director', max_length=100)),
                ('last_name', models.CharField(help_text='Apellido del director', max_length=100)),
                ('num_movies', models.PositiveSmallIntegerField(default=1, help_text='Numero de Movies Filmadas', max_length=50)),
                ('date_of_birth', models.DateField(blank=True, help_text='Edad Nacimiento', null=True)),
                ('date_of_death', models.DateField(blank=True, help_text='Fecha de Fallecimiento', null=True, verbose_name='Died')),
                ('oscars', models.CharField(blank=True, choices=[('s', 'Si'), ('n', 'No')], default='n', help_text='Indique si ha ganado un oscar', max_length=1)),
                ('num_oscars', models.PositiveSmallIntegerField(default=0, help_text='Indique el numero de Oscars Ganados', max_length=20, null=True)),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Genero de la Movie', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la Película', max_length=120)),
                ('premiere_date', models.DateField()),
                ('execution_time', models.PositiveSmallIntegerField()),
                ('summary', models.TextField(help_text='Descripcion de la Movies', max_length=100)),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cartelera.director')),
                ('genre', models.ManyToManyField(to='cartelera.genre')),
            ],
        ),
    ]
