# Generated by Django 4.0.4 on 2022-04-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartelera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='num_movies',
            field=models.PositiveSmallIntegerField(default=1, help_text='Numero de Movies Filmadas'),
        ),
        migrations.AlterField(
            model_name='director',
            name='num_oscars',
            field=models.PositiveSmallIntegerField(default=0, help_text='Indique el numero de Oscars Ganados', null=True),
        ),
    ]
